name = "nebula_beam"
version = "1.0.0"

# description = ""
# licences = ["Apache-2.0"]
# repository = { type = "github", user = "", repo = "" }
# links = [{ title = "Website", href = "" }]

[dependencies]
gleam_stdlib = ">= 0.44.0 and < 2.0.0"
glats = { git = "https://github.com/SrGaabriel/glats", ref="main" }
gleam_erlang = "~> 1.3.0"
dotenv = ">= 3.1.0 and < 4.0.0"
envoy = ">= 1.0.2 and < 2.0.0"
gleam_otp = ">= 1.1.0 and < 2.0.0"
mist = "~> 5.0.3"
gleam_http = "~> 4.2.0"
gleam_yielder = "~> 1.1.0"
logging = "~> 1.3.0"
gwt = ">= 2.1.2 and < 3.0.0"
dynamic = ">= 0.1.2 and < 1.0.0"
gleam_json = ">= 3.0.2 and < 4.0.0"
